#!/bin/bash
while : ; do
    period=`cat /etc/bsr.d/.bsrmon_period 2>&1`
    if [ $? -ne 0 ];then
        period=1
    fi
    sleep $period

    # run bsrmon
    # BSR-796 check if the bsr kernel module is running
    check_mod=`lsmod | grep -w bsr | wc -l`
    if [ $check_mod -gt 0 ]; then
        bsrmon /file &> /dev/null
    fi
done
