#!/bin/bash
#*******************************************************************************
# Copyright(c)2007-2020 ManTechnology Co., LTD. All rights reserved.
#*******************************************************************************

##########################################################################################
# Variable
##########################################################################################

BSR_LOG_PATH=`bsrcon /get_log_path`
# BSR-1215
BSRMON_FILE_PATH=`bsrmon /get file_path`
# BSR-1260
BSRMON_FILE_PATH=$(echo $BSRMON_FILE_PATH | cut -d ':' -f2)

BSRSUPPORT_LOG=$BSR_LOG_PATH/bsrsupport.log
echo [`date "+%Y-%m-%d_%H:%M:%S.%2N"`] [bsrsupport] start. > $BSRSUPPORT_LOG

# BSR-1130
Logging()
{
	echo -e ${1}
	echo -e [`date "+%Y-%m-%d_%H:%M:%S.%2N"`] ${1} >> $BSRSUPPORT_LOG
}

Logging "[Check environments] start.";

BSR_PATH=/opt/bsr
HOSTNAME=`hostname`
SUPPORT_HOME=${BSR_PATH}/support


# BSR-976 add option to exclude system log collection to bsrsupport
# BSR-1117 add bsrsupport options --exclude-system-log, --exclude-perfmon
for arg in "$@"
do
	if [ "$arg" = "-exclude_systemlog" ]; then
		EXCLUDE_SYSLOG=true
	elif [ "$arg" = "--exclude-system-log" ]; then
		EXCLUDE_SYSLOG=true
	elif [ "$arg" = "--exclude-perfmon" ]; then
		EXCLUDE_PERFMON=true
	else
		CORE_FILE_PATH=${arg}
	fi

done

# Target directory path that collected BSR files are located. This is not a BSR home path.
BSR_DIR=${SUPPORT_HOME}/${HOSTNAME}/bsr
# Target directory path that collected system files are located.
SYS_DIR=${SUPPORT_HOME}/${HOSTNAME}/System

if [ ! ${BSR_PATH} ]; then
	Logging "BSR not installed"
	exit -1
fi

if [ ! $BSR_CONF_FILE ]; then
	Logging "use default BSR configuration file"
	BSR_CONF_FILE=/etc/bsr.conf
else
	Logging "BSR configuration file: "$BSR_CONF_FILE
fi
Logging "[Check environments] complete.";


##########################################################################################
# Functions                                                                              #
##########################################################################################
GetBSRInfo()
{
	Logging "Get BSR Information...";

	BSR_CFG_DIR=${BSR_DIR}/conf
	BSR_MOD_DIR=${BSR_DIR}/module
	BSR_LOG_DIR=${BSR_DIR}/log
	BSR_MON_DIR=${BSR_DIR}/perfmon

	mkdir -p ${BSR_DIR}
	mkdir -p ${BSR_CFG_DIR}
	mkdir -p ${BSR_MOD_DIR}
	mkdir -p ${BSR_LOG_DIR}
	if [ 0 -eq ${#EXCLUDE_PERFMON} ]; then
		mkdir -p ${BSR_MON_DIR}
	fi
	if [ -e /proc/bsr ]; then
		cat /proc/bsr > ${BSR_DIR}/bsr_state
		Logging "bsr_state"
		bsradm show-gi all > ${BSR_DIR}/GI_state
		Logging "GI_state"
		cp -rL /sys/module/bsr/* ${BSR_MOD_DIR} 2> /dev/null
		Logging "Get bsr module info"
	else
		Logging "bsr module not found."
	fi

	cp -rL /etc/bsr.d/* ${BSR_CFG_DIR} && find ${BSR_CFG_DIR} -type f ! -iname "*.res" -delete
	cp -L /etc/bsr.conf ${BSR_DIR}
	Logging "Get bsr config"
	if [ -f /etc/bsr.d/global_common.conf ]; then
		cp -L /etc/bsr.d/global_common.conf ${BSR_CFG_DIR}
	fi

	if [ ! $BSR_CONF_FILE ]; then
		bsradm dump > ${BSR_DIR}/dump
	else
		bsradm dump --config-file=$BSR_CONF_FILE > ${BSR_DIR}/dump
	fi

	if [ -d $BSR_LOG_PATH ]; then
		# BSR-1117
		cp -rL ${BSR_LOG_PATH}/bsr.log* ${BSR_LOG_DIR} 2> /dev/null
		cp -rL ${BSR_LOG_PATH}/bsradm.log* ${BSR_LOG_DIR} 2> /dev/null
		cp -rL ${BSR_LOG_PATH}/bsrsetup.log* ${BSR_LOG_DIR} 2> /dev/null
		cp -rL ${BSR_LOG_PATH}/bsrmeta.log* ${BSR_LOG_DIR} 2> /dev/null
		cp -rL ${BSR_LOG_PATH}/bsrapp.log* ${BSR_LOG_DIR} 2> /dev/null
		cp -rL ${BSR_LOG_PATH}/xfs_logprint*.log ${BSR_LOG_DIR} 2> /dev/null
		cp -rL ${BSR_LOG_PATH}/xfs_repair*.log ${BSR_LOG_DIR} 2> /dev/null
		cp -rL ${BSR_LOG_PATH}/tune2fs*.log ${BSR_LOG_DIR} 2> /dev/null
		cp -rL ${BSR_LOG_PATH}/fsck*.log ${BSR_LOG_DIR} 2> /dev/null
		Logging "Get bsr log"
	else
		Logging "bsr log (${BSR_LOG_PATH}) not found."
	fi

	if [ 0 -eq ${#EXCLUDE_PERFMON} ]; then
		if [ -d $BSRMON_FILE_PATH ]; then
			cp -rL ${BSRMON_FILE_PATH}/* ${BSR_MON_DIR} 2> /dev/null
			Logging "Get bsr perfmon log"
		else
			Logging "bsrmon file path (${BSRMON_FILE_PATH}) not found."
		fi
	else
		Logging "skip collection of perfmon log."
	fi

}

GetSystemInfo()
{
	Logging "Get System information..."

	# Logs
	mkdir -p ${SYS_DIR}
	dmesg > ${SYS_DIR}/dmeg
	if [ -e "/var/log/messages" ]; then
		cp -L /var/log/messages* ${SYS_DIR}/
		Logging "messages"
	elif [ -e "/var/log/syslog" ]; then
		cp -L /var/log/syslog ${SYS_DIR}/
		Logging "syslog"
	else
		echo "/var/log/systemlog doesn't exit" > ${SYS_DIR}/none_messages_syslog
		Logging "none_messages_syslog"
	fi
	cp -L /var/log/*.log ${SYS_DIR}/

	# Current states
	w > ${SYS_DIR}/w
	who -r > ${SYS_DIR}/who_r
	last >> ${SYS_DIR}/lastlog
	runlevel > ${SYS_DIR}/runlevel
	Logging "current states"

	# OS
	uname -a > ${SYS_DIR}/uname_a
	cat /etc/*release >> ${SYS_DIR}/os_release
	Logging "OS"

	# Hardware
	cat /proc/cpuinfo > ${SYS_DIR}/cpuinfo
	cat /proc/meminfo > ${SYS_DIR}/meminfo
	dmidecode > ${SYS_DIR}/dmidecode
	free -m > ${SYS_DIR}/free

	if [ -e "/bin/rpm" ]; then				# Redhat RPM list
		/bin/rpm -qa >  ${SYS_DIR}/rpm_list
	elif [ -e "/usr/bin/dpkg" ]; then		# devian package list
		dpkg -l >  ${SYS_DIR}/dpkg_list
	else
		echo "package manager doesn't exist" > ${SYS_DIR}/none_pkg_list;
		Logging "none_pkg_list"
	fi
	Logging "hardware"

	# Network Information
	ip addr > ${SYS_DIR}/ifconfig_a
	if [ -e "/usr/sbin/ethtool" ]; then
		for i in `ip addr | egrep "*: eth*|*: bond*" | awk '{ print $2}' | awk -F':' '{ print $1}'`; do ethtool $i; done > ${SYS_DIR}/ethtoollog
	elif [ -e "/usr/bin/lshw" ] || [ -e "/usr/sbin/lshw" ]; then
		lshw -class network > ${SYS_DIR}/ethtoollog
	else
		echo "ethtoollog doesn't exit" > ${SYS_DIR}/none_ethtoollog
		Logging "none_ethtoollog"
	fi

	if ( which route > /dev/null 2>&1 ); then
		route -n > ${SYS_DIR}/route
	else
		ip -d route > ${SYS_DIR}/route
	fi
	if ( which netstat > /dev/null 2>&1 ); then
		netstat -nap > ${SYS_DIR}/netstat
		netstat -nr > ${SYS_DIR}/netstat_nr
	else
		ss -nap > ${SYS_DIR}/ss
	fi

	if [ -e "/etc/netplan" ]; then # debian 
		cp -L /etc/netplan/*  ${SYS_DIR}/
	elif [ -e "/etc/network/interfaces" ]; then			# debian(legacy)
		cp -L /etc/network/interfaces ${SYS_DIR}/sysconfignetworkfile
	elif [ -e "/etc/NetworkManager/system-connections" ]; then	 # redhat	
		cp -L /etc/NetworkManager/system-connections/* ${SYS_DIR}/sysconfignetworkfile
	elif [ -f "/etc/sysconfig/network" ]; then			# redhat(legacy)
		cp -L /etc/sysconfig/network  ${SYS_DIR}/sysconfignetworkfile
		cp -L /etc/sysconfig/network-scripts/*  ${SYS_DIR}/
	elif [ -d "/etc/sysconfig/network" ]; then 		    # suse
		for file in /etc/sysconfig/network/*; do
			if [ -f "$file" ]; then
				filename=$(basename "$file")
				if [ "$filename" != "ifcfg-lo" ] && [ "$filename" != "ifcfg.template" ]; then
					cp -L "$file" ${SYS_DIR}/sysconfignetworkfile
				fi
			fi
		done
	else
		echo "sysconfig-network doesn't exit" > ${SYS_DIR}/none_sysconfignetworkfile
		Logging "none_sysconfignetworkfile"
	fi

	cp -L /etc/hosts ${SYS_DIR}/
	cp -L /etc/host.conf ${SYS_DIR}/

	if [ -e "/etc/hosts.deny" ]; then
		cp -L /etc/hosts.deny ${SYS_DIR}/
	else
		echo "/etc/hosts.deny doesn't exit" > ${SYS_DIR}/none_hosts.deny
		Logging "none_hosts.deny"
	fi
	if [ -e "/etc/hosts.allow" ]; then
		cp -L /etc/hosts.allow ${SYS_DIR}/
	else
		echo "/etc/hosts.allow doesn't exit" > ${SYS_DIR}/none_hosts.allow
		Logging "none_hosts.allow"
	fi
	Logging "network"

	# Bonding Information
	BON_DIR="/proc/net/bonding"
	if [ -e ${BON_DIR} ]; then
		cp -rL ${BON_DIR} ${SYS_DIR}
	fi

	SKEL_DIR=${SYS_DIR}/skel
	USR_DIR=${SYS_DIR}/User

	mkdir -p ${SKEL_DIR}
	mkdir -p ${USR_DIR}

	Logging "bonding"

	# sshd_config
	if [ -e /etc/ssh/sshd_config ]; then
		cp -L /etc/ssh/sshd_config ${SYS_DIR}/
		Logging "sshd_config"
	fi

	# bash info
	if [ -e "/etc/skel/.bash_logout" ]; then
		cp -L /etc/skel/.bash_logout ${SKEL_DIR}/bash_logout
	else
		echo "/etc/skel/.bash_logout doesn't exit" > ${SKEL_DIR}/none_bash_logout
		Logging "none_bash_logout"
	fi

	if [ -e "/etc/skel/.bash_profile" ]; then				# redhat
		cp -L /etc/skel/.bash_profile ${SKEL_DIR}/bash_profile
	elif [ -e "/etc/skel/.profile" ]; then					# devian
		cp -L /etc/skel/.profile ${SKEL_DIR}/profile
	else
		echo "bash profile doesn't exit" > ${SKEL_DIR}/none_bash_profile
		Logging "none_bash_profile"
	fi

	if [ -e "/etc/skel/.bashrc" ]; then
		cp -L /etc/skel/.bashrc ${SKEL_DIR}/bash_bashrc
	else
		echo "/etc/skel/.bashrc doesn't exit" > ${SKEL_DIR}/none_bashrc
		Logging "none_bashrc"
	fi

	if [ -e /root/.bash_profile ]; then					# redhat
		cp -L /root/.bash_profile ${USR_DIR}/root_profile
	elif [ -e /root/.profile ]; then					# devian
		cp -L /root/.profile ${USR_DIR}/root_profile
	else
		echo "/root/.profile doesn't exit" > ${USR_DIR}/none_root_profile
		Logging "none_root_profile"
	fi

	if [ -e "/root/.bashrc" ]; then
		cp -L /root/.bashrc ${USR_DIR}/root_bashrc
	else
		echo "/root/.bashrc doesn't exit" > ${USR_DIR}/none_root_bashrc
	fi

	Logging "bash info"

	# system config
	ETC_CFG_DIR=${SYS_DIR}/etcConfig
	RC_CFG_DIR=${SYS_DIR}/rcConfig
	MODPROBE_DIR=${SYS_DIR}/modprobe.d
	ETC_FSTAB_DIR=${SYS_DIR}/etcFstab

	mkdir -p ${ETC_CFG_DIR}/
	mkdir -p ${RC_CFG_DIR}/
	mkdir -p ${MODPROBE_DIR}/
	mkdir -p ${ETC_FSTAB_DIR}/

	cp -rL /etc/*.conf ${ETC_CFG_DIR}/
	cp -rnL /etc/rc*.d/* ${RC_CFG_DIR}/
	cp -rL /etc/fstab* ${ETC_FSTAB_DIR}/

	Logging "system config"

	# device list
	cp -L /etc/modprobe.d/*  ${MODPROBE_DIR}
	ls -l /dev  > ${SYS_DIR}/deviceList
	lsmod > ${SYS_DIR}/lsmodList
	Logging "device list"

	# disk Information
	lsblk > ${SYS_DIR}/lsblk
	mount > ${SYS_DIR}/mount
	fdisk -l > ${SYS_DIR}/fdisk
	if [ -e "/usr/bin/lsscsi" ]; then
		lsscsi > ${SYS_DIR}/lsscsi
	fi
	if [ -e "/usr/bin/lshw" ] || [ -e "/usr/sbin/lshw" ]; then
		lshw -c disk > ${SYS_DIR}/lshw_disk
	fi
	Logging "disk Information"

	# Process Information
	ps -ALf > ${SYS_DIR}/processInfo
	Logging "processInfo"
	# sysctl Information
	sysctl -a > ${SYS_DIR}/sysCtlInfo 2> /dev/null
	Logging "sysCtlInfo"

	# system configure
	SELIX_DIR=${SYS_DIR}/selinux

	mkdir -p ${SELIX_DIR}/

	ps -ewwwf > ${SYS_DIR}/ps_output
	uptime >  ${SYS_DIR}/uptime

	if [ -e "/etc/selinux/config" ]; then
		cp -L /etc/selinux/config ${SELIX_DIR}/
	else
		echo "/etc/selinux/config doesn't exit." > ${SELIX_DIR}/none_selinux_config
		Logging "none_selinux_config"
	fi
	Logging "system configure"

	# services
	if ( which service > /dev/null 2>&1 ); then
		service --status-all > ${SYS_DIR}/service_status_all
	fi

	if ( which chkconfig > /dev/null 2>&1 ); then
		chkconfig --list > ${SYS_DIR}/chkconfig_list 2> /dev/null
	fi

	if ( which systemctl > /dev/null 2>&1 ); then
		systemctl list-unit-files --type=service -q --no-pager >> ${SYS_DIR}/systemctl_list 
	fi

	Logging "service"

	# firewalls
	if [ -f "/sbin/iptables" ]; then			# redhat 6, 7, devian
		iptables -L  > ${SYS_DIR}/iptableList
	fi

	if [ -f "/usr/bin/firewall-cmd" ]; then			# redhat 7
		firewall-cmd --list-all > ${SYS_DIR}/firewalld_list_all
		firewall-cmd --zone=public --list-ports > ${SYS_DIR}/firewalld_public
		firewall-cmd --permanent --zone=public --list-ports > ${SYS_DIR}/firewalld_permanent_public
	fi
	Logging "firewalls"
}

GetBSRStatus()
{
	Logging "Get BSR Status information...";

	BSR_STATUS_DIR=${BSR_DIR}/status

	mkdir -p ${BSR_STATUS_DIR}

	bsradm show-gi all > ${BSR_STATUS_DIR}/gi.txt
	bsradm dump > ${BSR_STATUS_DIR}/dump.txt
	bsrsetup status --s --v all > ${BSR_STATUS_DIR}/status.txt
	bsrsetup show > ${BSR_STATUS_DIR}/show.txt
}

Archive()
{
	Logging "Archive files..."

	if [ -d ${SUPPORT_HOME}/${HOSTNAME} ]; then
		dt=$(date '+%Y%m%d.%H%M%S');
		ARCHIVE_NAME=${HOSTNAME}-$dt.tar.gz

		cd ${SUPPORT_HOME}
		tar --remove-files -zcvf "${SUPPORT_HOME}/${ARCHIVE_NAME}" ${HOSTNAME}

		echo ""
		Logging "Saved to ${SUPPORT_HOME}/${ARCHIVE_NAME}"
	else
		Logging "No gathered information."
	fi
}

GetCoreDumpFile()
{
	if [ 0 -ne ${#1} ]; then
		filename=$(basename ${1})
		filepath=$(dirname ${1})

		if [ ! -d "${BSR_DIR}" ]; then
			/bin/mkdir -p "${BSR_DIR}";
		fi

		dst_core_filename="${BSR_DIR}/${filename}.tar.gz"
		/bin/tar zcvf ${dst_core_filename} -C ${filepath} ${filename};

		Logging "core file has been compressed.";
	else
		Logging "core file is not included.";
	fi
}

# BSR-675 add debugfs info to support file
GetBSRDebugfs()
{
	Logging "Get BSR debugfs...";

	DEBUGFS_DIR=${BSR_DIR}/debugfs
	mkdir -p ${DEBUGFS_DIR}

	if [ -d /sys/kernel/debug/bsr ]; then
		cp -rL /sys/kernel/debug/bsr/* ${DEBUGFS_DIR}
	fi
}

##########################################################################################
# Main                                                                                   #
##########################################################################################

# Get Informations.
Logging "[GetCoreDumpFile] start."
GetCoreDumpFile "$CORE_FILE_PATH"
Logging "[GetCoreDumpFile] complete."
Logging "[GetBSRInfo] start."
GetBSRInfo
Logging "[GetBSRInfo] complete."

# BSR-976 add option to exclude system log collection to bsrsupport
if [ 0 -eq ${#EXCLUDE_SYSLOG} ]; then
	Logging "[GetSystemInfo] start."
	GetSystemInfo
	Logging "[GetSystemInfo] complete."
else
	Logging "skip collection of system log."
fi
Logging "[GetBSRStatus] start."
GetBSRStatus
Logging "[GetBSRStatus] complete."
Logging "[GetBSRDebugfs] start."
GetBSRDebugfs
Logging "[GetBSRDebugfs] complete."
Logging "[Archive] start."
Archive
Logging "[Archive] complete."

echo [`date "+%Y-%m-%d_%H:%M:%S.%2N"`] [bsrsupport] complete. >> $BSRSUPPORT_LOG