



#define BSRLOCK_VOLUMENAME_MAX_LEN	260

#ifndef _BSRLOCK_STRUCT_
#define _BSRLOCK_STRUCT_

enum VOLUME_NAME_TYPE
{
	VOLUME_TYPE_LETTER,
	VOLUME_TYPE_GUID,
	VOLUME_TYPE_DEVICE_NAME,
	VOLUME_TYPE_DEVICE_OBJECT,
};

typedef struct _BSRLOCK_VOLUME {
	enum VOLUME_NAME_TYPE volumeType;
	union
	{
		WCHAR volumeName[BSRLOCK_VOLUMENAME_MAX_LEN];
		PVOID pVolumeObject;
	}volumeID;
	
}BSRLOCK_VOLUME, *PBSRLOCK_VOLUME;

#endif